import { Sidebar } from "@/components/Sidebar/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/lib/providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider />
        <main className="flex flex-row min-h-screen">
          <section className="w-fit">
            <Sidebar />
          </section>
          <section className="flex-1">{children}</section>
        </main>
      </body>
    </html>
  );
}
